# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("general", "0003_auto_20180220_0537")]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="project",
            field=models.BooleanField(default=False),
        )
    ]
