# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-26 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("general", "0004_subject_project")]

    operations = [
        migrations.AddField(
            model_name="teaches", name="ug", field=models.BooleanField(default=False)
        )
    ]
