# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-13 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("general", "0005_teaches_ug")]

    operations = [
        migrations.AddField(
            model_name="teaches",
            name="count",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Student Count"
            ),
        ),
        migrations.AlterField(
            model_name="teaches",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="general.Department"
            ),
        ),
    ]
