# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-29 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("general", "0007_message")]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_text",
            field=models.TextField(
                max_length=350, verbose_name="Message to send to students"
            ),
        )
    ]
