# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-05 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_auto_20180429_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.TextField(max_length=1000, verbose_name='Message to send to students'),
        ),
    ]
