# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-16 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_auto_20181105_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Subject Code'),
        ),
    ]
