# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-18 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("feedback", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="feedbackform",
            name="active",
            field=models.BooleanField(default=True),
        )
    ]
