# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-06 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("feedback", "0003_auto_20180303_0652")]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="feedback.FeedbackForm",
            ),
        )
    ]
