# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-06 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("feedback", "0004_answer_user")]

    operations = [
        migrations.RenameField(model_name="answer", old_name="user", new_name="form")
    ]
