# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-20 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_auto_20180315_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidatedReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of faculty')),
                ('form_name', models.CharField(max_length=100, verbose_name='Name of the form')),
                ('total', models.CharField(max_length=10, verbose_name='Total value they got')),
                ('department', models.CharField(max_length=30, verbose_name='Department')),
            ],
        ),
    ]
