# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-20 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("feedback", "0007_consolidatedreport")]

    operations = [
        migrations.AlterField(
            model_name="consolidatedreport",
            name="department",
            field=models.CharField(max_length=30, verbose_name="Department Code"),
        )
    ]
