# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-20 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("feedback", "0008_auto_20180320_0935")]

    operations = [
        migrations.RenameField(
            model_name="consolidatedreport", old_name="department", new_name="dep"
        )
    ]
