# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-20 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("feedback", "0010_remove_consolidatedreport_dep")]

    operations = [
        migrations.AddField(
            model_name="consolidatedreport",
            name="department",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Department Code"
            ),
        )
    ]
