# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("feedback", "0012_studentanswer")]

    operations = [
        migrations.AlterField(
            model_name="studentanswer",
            name="value",
            field=models.CharField(
                choices=[
                    ("Excellent", "Excellent"),
                    ("Good", "Good"),
                    ("Satisfactory", "Satisfactory"),
                    ("Poor", "Poor"),
                    ("Very Poor", "Very Poor"),
                ],
                max_length=60,
            ),
        )
    ]
