# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0013_auto_20180327_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentConsolidatedReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of faculty')),
                ('form_name', models.CharField(max_length=100, verbose_name='Name of the form')),
                ('total', models.CharField(max_length=10, verbose_name='Total value they got')),
                ('department', models.CharField(blank=True, max_length=30, null=True, verbose_name='Department Code')),
            ],
        ),
    ]
