# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20180413_0548'),
        ('feedback', '0014_studentconsolidatedreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentconsolidatedreport',
            name='form_name',
        ),
        migrations.AddField(
            model_name='studentconsolidatedreport',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.Teaches'),
        ),
    ]
