# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0015_auto_20180416_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentconsolidatedreport',
            name='total',
            field=models.IntegerField(max_length=10, verbose_name='Total value they got'),
        ),
    ]
