# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("feedback", "0016_auto_20180416_0747")]

    operations = [
        migrations.AlterField(
            model_name="studentconsolidatedreport",
            name="total",
            field=models.FloatField(max_length=10, verbose_name="Total value they got"),
        )
    ]
