# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-28 07:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0017_auto_20180416_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentconsolidatedreport',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2018, 9, 28, 7, 38, 21, 780522)),
            preserve_default=False,
        ),
    ]
