# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-15 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0018_studentconsolidatedreport_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentconsolidatedreport',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='No. of students'),
        ),
    ]
