# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-18 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ug',
            field=models.BooleanField(default=False),
        ),
    ]
