# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-16 18:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the department', max_length=250, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Subject Name')),
                ('code', models.CharField(max_length=50, verbose_name='Subject Code')),
                ('theory', models.BooleanField(default=True)),
                ('elective', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(max_length=50, verbose_name="Student's Semester")),
                ('sec', models.CharField(max_length=50, verbose_name="Student's Section")),
                ('batch', models.CharField(blank=True, max_length=50, null=True, verbose_name="Student's Batch")),
                ('sub_batch', models.CharField(blank=True, max_length=50, null=True, verbose_name="Student's sub batch")),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Department', verbose_name="Student's department")),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='batch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lab Batch'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Joining'),
        ),
        migrations.AddField(
            model_name='user',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='hod',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='partially_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sec',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='user',
            name='sem',
            field=models.IntegerField(blank=True, null=True, verbose_name='Semester'),
        ),
        migrations.AddField(
            model_name='user',
            name='sub_batch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lab Sub Batch'),
        ),
        migrations.AddField(
            model_name='user',
            name='vice_principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teaches',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.Department'),
        ),
        migrations.AddField(
            model_name='user',
            name='elective',
            field=models.ManyToManyField(blank=True, null=True, to='general.Subject'),
        ),
    ]
